apiVersion: v1
kind: Service
metadata:
  name: k8s-flask-scaffold-svc
spec:
  selector:
    app: k8s-flask-scaffold-app
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask-scaffold-app
spec:
  selector:
    matchLabels:
      app: k8s-flask-scaffold-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: k8s-flask-scaffold-app
    spec:
      containers:
      - name: eks-k8s-flask-scaffold
        image: 160443734003.dkr.ecr.us-east-1.amazonaws.com/playground-ecr-repo:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "400Mi"
